# Reference
# https://circleci.com/docs/2.0/configuration-reference

version: 2.1

jobs:
  build:
    parameters:
      image:
        type: string
        default: "ubuntu:latest"
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run:
          name: Update Aptitude Package Repositories
          command: apt update
      - run:
          name: Upgrade Packages
          command: apt upgrade -y
      - run:
          name: Install Build Tools
          command: apt install build-essential linux-headers-generic linux-headers-$(uname -r) -y
      - run:
          name: Build
          command: make

workflows:
  main:
    jobs:
      - build:
          name: "Ubuntu 20.04"
          image: "ubuntu:20.04"
      - build:
          name: "Ubuntu 19.10"
          image: "ubuntu:19.10"
      - build:
          name: "Ubuntu 18.04"
          image: "ubuntu:18.04"
